name: littleglyphs-cpu

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6.9
  - numpy=1.17.0
  - requests
  - pip
  - pip:
    - keras==2.2.4
    - matplotlib==3.1.1
    - pandas==0.25.0
    - tensorflow==1.12.0rc0
    - scikit-image==0.15.0
    - scikit-learn==0.21.3
    - scipy==1.3.0

